version: '2.4'
services:
  mysql:
    image: mysql:8.0.3
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "127.0.0.1:10001:80"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
#  app:
#    restart: always
#    image: potterua/a-line-test:latest
#    environment:
#      - MYSQL_HOST=mysql
#      - REDIS_HOST=redis
#    ports:
#      - 30300:80
