name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Prepare enviroments'
        run: |
          echo $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
          export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
      - name: Envs
        run: printenv
      - name: Login
        run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }} 
      - name: Build
        run: docker build -t docker.pkg.github.com/kodexxx/a-line-test/app:${VERSION} -t docker.pkg.github.com/kodexxx/a-line-test/app:latest .
      - name: Push
        run: |
          docker push docker.pkg.github.com/kodexxx/a-line-test/app:latest 
          docker push docker.pkg.github.com/kodexxx/a-line-test/app:${VERSION} 
